# 코틀린에서 예외를 다루는 방법
## 1. try catch finally 구문
1. 숫자인 경우 숫자를 반환하고, 아닌 경우 에러를 발생하는 try catch문을 작성해보자
```java
// Java
public int parseIntOrThrow(@NotNull String str) {
    try {
       return Integer.parseInt(str);
    } catch (NumberFormatException e) {
        throw new IllegalArgumentException(String.format("주어진 %s는 숫자가 아닙니다.", str));
    }
}
```
* Kotlin에서는 기본 타입간의 형변환은 toType()을 사용한다.
* toInt() 내부적으로는 Integer.parseInt()를 호출한다.
* exception을 생성할 때 `new`를 붙이지 않는다.
```kotlin
// Kotlin
fun parseIntOrThrow(str: String): Int {
    try {
        return str.toInt();
    } catch (e: NumberFormatException) {
        throw IllegalArgumentException("주어진 ${str}은 숫자가 아닙니다.")
    }
}
```
2. 주어진 문자열을 정수로 변환하는 예제, 실패시 null 반환
```kotlin
fun parseIntOrNull(str: String): Int? {
    return try {
        str.toInt();
    } catch (e: NumberFormatException) {
        null
    }
}
```
* Kotlin에서는 if-else와 같이 try-catch 구문도 하나의 Expression으로 간주된다.
* 따라서, try-catch 결과를 바로 반환할 수 있다.
